### ISSUE TITLE
Simplify CSS code for the font-weight property. 

### ISSUE THREAD

**Issue by josephtkim** [operales69/prj-rev-bwfs-dasmoto#7]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. You did a great job simplifying for the font-family property, and you can simplify it further for the font-weight property, like so

```css
h1, h2 {
  font-weight: bold;
}
```
